run:
  timeout: 5m
  tests: true
  skip-dirs:
    - internal/mocks
    - test/mocks

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  gocritic:
    settings:
      captLocal:
        paramsOnly: true
      rangeExprCopy:
        sizeThreshold: 16
        skipTestFuncs: true
  golint:
    min-confidence: 0.8
  gosec:
    excludes:
      - G104 # Errors unhandled
  lll:
    line-length: 120
  maligned:
    suggest-new: true
  misspell:
    locale: US
  unparam:
    check-exported: true
  depguard:
    rules:
      main:
        allow:
          - "github.com/Glitch-guy0/authService/modules/core"
          - "github.com/Glitch-guy0/authService/modules/logger"
          - "github.com/Glitch-guy0/authService/modules/config"
          - "github.com/Glitch-guy0/authService/modules/api/health"
          - "github.com/Glitch-guy0/authService/modules/version"
          - "github.com/Glitch-guy0/authService/modules/server"
          - "github.com/Glitch-guy0/authService/modules/core"
          - "github.com/Glitch-guy0/authService/modules/logger"
          - "github.com/Glitch-guy0/authService/pkg/errors"
          - "github.com/gin-gonic/gin"
          - "github.com/stretchr/testify/assert"
          - "github.com/stretchr/testify/require"
          - "github.com/stretchr/testify/mock"
          - "github.com/spf13/viper"
          - "github.com/sirupsen/logrus"
          - "github.com/google/uuid"
          - "github.com/go-playground/validator/v10"
          - "golang.org/x/net/context"
          - "context"
          - "fmt"
          - "os"
          - "time"
          - "net/http"
          - "net/http/httptest"
          - "sync"
          - "encoding/json"
          - "strconv"
          - "strings"
          - "bytes"
          - "testing"
          - "os/exec"
          - "path/filepath"
          - "syscall"
          - "os/signal"
          - "runtime"
          - "runtime/debug"
          - "net/url"
          - "regexp"
          - "io"
          - "log"
          - "reflect"
          - "database/sql"
          - "math/rand"
          - "errors"

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
    - path: internal/mocks/.*
      linters:
        - unused
        - gosec
        - goconst
        - gocritic
        - gocyclo
        - gofmt
        - goimports
        - gosec
        - gosimple
        - govet
        - ineffassign
        - interfacer
        - lll
        - maligned
        - misspell
        - nakedret
        - prealloc
        - staticcheck
        - structcheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
